spring:
  application:
    name: authorizer
  datasource:
    url: jdbc:postgresql://localhost:5432/authorizer
    username: authorizer
    password: 123456

app:
  mcc:
    codes:
      food: ["5411", "5412"]
      meal: ["5811", "5812"]
  merchant:
    lists:
      restaurant: [ "McDonald's", "Burger King", "KFC", "Pizza Hut", "Starbucks" ]
      supermarket: [ "Walmart", "Carrefour", "Auchan", "Lidl", "Aldi" ]
      mobility: [ "Uber", "Lyft", "Didi", "Ola", "Grab" ]
